name: paginated_text
description: "Paginated text view with auto-sized drop cap"
version: 0.0.1
repository: https://github.com/dra11y/drop_cap_text

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  collection: '^1.17.2'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
